name: Workload Identity Federation using in Terraform GCP Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: write
  actions: write
  checks: write
  deployments: write
  repository-projects: write
  id-token: write

jobs:
  # 📘 This job is used for creating the README file automatically.
  # It uses a reusable workflow hosted in your GitHub Actions repository.
  call-workflow-passing-data:
    uses: bikram-singh/github-actions/.github/workflows/reuseable-workflow-automate-readme.yml@main

  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # ✅ Authenticate to Google Cloud using Workload Identity Federation (WIF)
      - name: Authenticate to Google Cloud via WIF
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/1070327104780/locations/global/workloadIdentityPools/github-action-pool/providers/github-action'
          service_account: 'github-wif@github-actions-111.iam.gserviceaccount.com'

      # ❌ Old method using Service Account Key (commented for reference)
      # - name: Authenticate to Google Cloud
      #   id: auth
      #   uses: google-github-actions/auth@v2
      #   with:
      #     credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
